### PR TITLE
upped compatibility

### PR DESCRIPTION
**Pull request by bvdbos**
for v2 compatibility, think it works

### CODE REVIEW

**Comment by MenneBos** [comment]
I installed successfully the SSH Client on my Homey 2.0 via the CLI method.....I replaced the original app.json file with the new created one in the PR. Tx

**Comment by jimvlambe** [comment]
Now working with Homey v2.1.1

**Comment by kerkenit** [comment]
@bvdbos Is it OK I transfer the app to you? Please send me your user_id in a private message

**Comment by kerkenit** [comment]
I can't publish it to the store. I got the message: Your app uses Apps SDK v1. Only Apps SDK v2 or higher is supported.

**Pull request merged**
